# replace the values with corresponding values at the ASI you are connecting to
production:
  ASI: '0.0.0.0'
  ASI_app_name: 'ASI_app_name_goes_here'
  ASI_app_password: 'ASI_app_password_goes_here'
  
development: &non_production_settings
  ASI: '0.0.0.0'
  ASI_app_name: 'ASI_app_name_goes_here'
  ASI_app_password: 'ASI_app_password_goes_here'
  
test:
  <<: *non_production_settings

